languages = {
            'ANG': {
                'Percent: ': 'Percent: ',
                "JOB HUNT HELPER": "JOB HUNT HELPER",
                'VIEW ALL': 'VIEW ALL',
                'ADD': 'ADD',
                'SAVE': 'SAVE',
                "SEARCH": "SEARCH",
                "EDIT": 'EDIT',
                'FIND': 'FIND',
                'SAVE CHANGES': 'SAVE CHANGES',
                'DELETE': 'DELETE',
                'MENU': 'MENU',
                'Job Name': 'Job Name',
                'Job Type': 'Job Type',
                'Public Transport': 'Public Transport',
                'Job Address': 'Job Address',
                'Date Applied': 'Date Applied',
                'Job Status': 'Job Status',
                "Job Name:": "Job Name:",
                "Job Type:": "Job Type:",
                "Tram/Bus stop:": "Tram/Bus stop:",
                "Job Address:": "Job Address:",
                "Date (DD-MM-YYYY):": "Date (DD-MM-YYYY):",
                "Job Status:": "Job Status:",
                "job name": "job name",
                "date": "date",
                "status": "status",
                "type": "type",
                "bus/tram stop": "bus/tram stop",
                "SEARCH BY": "SEARCH BY",
                "VIEW STATS": "VIEW STATS",
                'AVERAGE APPS PER DAY': 'AVERAGE APPS PER DAY',
                'JOBS PER STATUS': 'JOBS PER STATUS',
                'JOBS PER TYPE': 'JOBS PER TYPE',
                'JOBS PER DATE': 'JOBS PER DATE',
                'APPLICATIONS IN PAST WEEK': 'APPLICATIONS IN PAST WEEK',
                'SHOW CHART': 'SHOW CHART',
                'SHOW TABLE': 'SHOW TABLE',
                'No job data added yet': 'No job data added yet',
                'Please select a job to delete.': 'Please select a job to delete.',
                'Please select an option from the dropdown menu.': 'Please select an option from the dropdown menu.',
                'No entries found.': 'No entries found.',
                'No data found. Please add a job then try again.': 'No data found. Please add a job then try again.',
                'Please select a job to edit.': 'Please select a job to edit.',
                "HIDE CHART": "HIDE CHART",
                "HIDE TABLE": "HIDE TABLE",
                "Average Apps per Day:": "Average Apps per Day:",
                'Amount:': 'Amount:',
                'Percent:': 'Percent:',
                "Jobs per Status:": "Jobs per Status:",
                "Jobs per Type:": "Jobs per Type:",
                "Jobs per Date:": "Jobs per Date:",
                "Apps sent out last week:": "Apps sent out last week:",
                "CHOOSE LANGUAGE": "CHOOSE LANGUAGE",
                "SELECT LANGUAGE": "SELECT LANGUAGE",
                "Check if everything is correct": "Check if everything is correct",
                'Job Name: ': 'Job Name: ',
                'Job Type: ': 'Job Type: ',
                'Public Transport: ': 'Public Transport: ',
                'Job Address: ': 'Job Address: ',
                'Date Applied: ': 'Date Applied: ',
                'Job Status: ': 'Job Status: ',
                "Are you sure?": "Are you sure?",
                "Please duble check you want to proceed": "Please duble check you want to proceed",
                'Please enter date in DD-MM-YYYY format.': 'Please enter date in DD-MM-YYYY format.',
                'Only Tram/Bus stop field can be left empty.': 'Only Tram/Bus stop field can be left empty.',
                'Job applications sent out last week': 'Job applications sent out last week',
                'Date': 'Date',
                'Job applications':'Job applications',
                'Jobs per ': 'Jobs per ',
                'Categories': 'Categories',
                'Job count': 'Job count',
                'Settings': 'Settings',
                'Amount: ': 'Amount: '
            },
            'PL': {
                "JOB HUNT HELPER": "ASYSTENT POSZUKIWANIA PRACY",
                'VIEW ALL': 'ZOBACZ WSZYSTKO',
                'ADD': 'DODAJ',
                'SAVE': 'ZAPISZ',
                "SEARCH": "ZNAJDŹ",
                "EDIT": 'EDYTUJ',
                'FIND': 'SZUKAJ',
                'SAVE CHANGES': 'ZAPISZ ZMIANY',
                'DELETE': 'USUŃ',
                'MENU': 'MENU',
                'Job Name': 'Nazwa Pracodawcy',
                'Job Type': 'Rodzaj Pracy',
                'Public Transport': 'Przystanki w pobliżu',
                'Job Address': 'Siedziba Pracy',
                'Date Applied': 'Data złożenia CV',
                'Job Status': 'Status',
                "Job Name:": "Nazwa Pracodawcy:",
                "Job Type:": "Rodzaj Pracy:",
                "Tram/Bus stop:": "Przystanki w pobliżu:",
                "Job Address:": "Siedziba Pracy:",
                "Date (DD-MM-YYYY):": "Data (DD-MM-RRRR):",
                "Job Status:": "Status:",
                "job name": "nazwa pracodawcy",
                "date": "data",
                "status": "status",
                "type": "rodzaj",
                "bus/tram stop": "przystanki",
                "SEARCH BY": "OPCJE",
                "VIEW STATS": "STATYSTYKI",
                'AVERAGE APPS PER DAY': 'ŚREDNIA CV/DZIEŃ',
                'JOBS PER STATUS': 'STATUS',
                'JOBS PER TYPE': 'RODZAJ',
                'JOBS PER DATE': 'DATA',
                'APPLICATIONS IN PAST WEEK': 'CV ZŁOŻONE PRZEZ OSTATNIE 7 DNI',
                'SHOW CHART': 'POKAŻ WYKRES',
                'SHOW TABLE': 'POKAŻ TABELE',
                'No job data added yet': 'Jeszcze nie dodano żadnej pracy',
                'Please select a job to delete.': 'Wybierz prace do usunięcia',
                'Please select an option from the dropdown menu.': 'Proszę wybierz jedną z opcji',
                'No entries found.': 'Nic nie znaleziono.',
                'No data found. Please add a job then try again.': 'Nie znaleziono nic. Proszę dodaj wpis i sprubój ponownie.',
                'Please select a job to edit.': 'Wybierz wpis aby edytować',
                "HIDE CHART": "SCHOWAJ WYKRES",
                "HIDE TABLE": "SCHOWAJ TABELE",
                "Average Apps per Day:": "Średnia CD/DZIEŃ:",
                'Amount: ': 'Ilość:',
                'Percent: ': 'Procent:',
                "Jobs per Status:": "Prace podzielone na status:",
                "Jobs per Type:": "Prace podzielone na rodzaj:",
                "Jobs per Date:": "Prace podzielone na date złorzenia CV:",
                "Apps sent out last week:": "CV złożone przez ostatnie 7 dni:",
                "CHOOSE LANGUAGE": "WYBIERZ JĘZYK",
                "SELECT LANGUAGE": "WYBIERZ JĘZYK",
                "Check if everything is correct": "Sprawdź czy wszystko się zgadza",
                'Job Name: ': 'Nazwa Pracodawcy: ',
                'Job Type: ': 'Rodzaj Pracy: ',
                'Public Transport: ': 'Przystanki w poblirzu: ',
                'Job Address: ': 'Siedziba Pracy: ',
                'Date Applied: ': 'Data złożenia CV: ',
                'Job Status: ': 'Status: ',
                "Are you sure?": "Czy jesteś pewny/a?",
                "Please duble check you want to proceed": "Kontynuować?",
                'Please enter date in DD-MM-YYYY format.': 'Proszę wpisać date w formacie DD-MM-RRRR',
                'Only Tram/Bus stop field can be left empty.': 'Tylko informacja o pobliskich przystankach może pozostać nieuzupełniona.',
                'Job applications sent out last week': 'CV złożone przez ostatnie 7 dni',
                'Date': 'Data',
                'Job applications': 'Złożone CV',
                'Jobs per ': 'Prace na ',
                'Categories': 'Kategorie',
                'Job count': 'Iloś złożonych CV',
                'Settings': 'Ustawienia',
            },
            'ES': {
                "JOB HUNT HELPER": "AYUDANTE EN LA BÚSQUEDA DE EMPLEO",
                'VIEW ALL': 'VER TODO',
                'ADD': 'AÑADIR',
                'SAVE': 'GUARDAR',
                "SEARCH": "BUSCAR",
                "EDIT": 'EDITAR',
                'FIND': 'BUSCAR',
                'SAVE CHANGES': 'GUARDAR CAMBIOS',
                'DELETE': 'BORRAR',
                'MENU': 'MENÚ',
                'Job Name': 'Nombre del trabajo',
                'Job Type': 'Tipo de trabajo',
                'Public Transport': 'Paradas de ransporte público',
                'Job Address': 'Dirección',
                'Date Applied': 'Fecha de solicitud',
                'Job Status': 'Status',
                "Job Name:": "Nombre del trabajo:",
                "Job Type:": "Tipo de trabajo:",
                "Tram/Bus stop:": "Paradas de ransporte público:",
                "Job Address:": "Dirección:",
                "Date (DD-MM-YYYY):": "Fecha (DD-MM-AAAA):",
                "Job Status:": "Status:",
                "job name": "nombre del trabajo",
                "date": "fecha",
                "status": "status",
                "type": "tipo",
                "bus/tram stop": "paradas",
                "SEARCH BY": "OPCIONES",
                "VIEW STATS": "VER ESTADÍSTICAS",
                'AVERAGE APPS PER DAY': 'PROMEDIO POR DÍA',
                'EMPLEOS POR STATUS': 'STATUS',
                'JOBS PER TYPE': 'TRABAJOS POR TIPO',
                'JOBS PER DATE': 'TRABAJOS POR FECHA',
                'APPLICATIONS IN PAST WEEK': 'SOLICITUDES EN LA ÚLTIMA SEMANA',
                'SHOW CHART': 'MOSTRAR GRÁFICO',
                'SHOW TABLE': 'MOSTRAR TABLA',
                'No job data added yet': 'Aún no se han agregado datos del trabajo',
                'Please select a job to delete.': 'Seleccione un trabajo para eliminar.',
                'Please select an option from the dropdown menu.': 'Seleccione una opción del menú desplegable.',
                'No entries found.': 'No se encontraron datos.',
                'No data found. Please add a job then try again.': 'No se encontraron datos. Agregue un trabajo y vuelva a intentarlo.',
                'Please select a job to edit.': 'Seleccione un trabajo para editar.',
                "HIDE CHART": "OCULTAR GRÁFICO",
                "HIDE TABLE": "OCULTAR TABLA",
                "Average Apps per Day:": "Aplicaciones promedio por día:",
                'Amount:': 'Cantidad:',
                'Percent:': 'Porcentaje:',
                "Jobs per Status:": "Empleos por status:",
                'JOBS PER STATUS': "EMPLEOS POR STATUS:",
                "Jobs per Type:": "Trabajos por tipo:",
                "Jobs per Date:": "Trabajos por fecha:",
                "Apps sent out last week:": "solicitudes enviadas la semana pasada:",
                "CHOOSE LANGUAGE": "ELEGIR IDIOMA",
                "SELECT LANGUAGE": "ELEGIR IDIOMA",
                "Check if everything is correct": "Comprueba si todo es correcto.",
                'Job Name: ': 'Nombre del trabajo: ',
                'Job Type: ': 'Tipo de trabajo: ',
                'Public Transport: ': 'Paradas de transporte público: ',
                'Job Address: ': 'Dirección de trabajo: ',
                'Date Applied: ': 'Fecha de solicitud: ',
                'Job Status: ': 'Status: ',
                "Are you sure?": "Estas seguro/a",
                "Please duble check you want to proceed": "Por favor verifique que desea continuar",
                'Please enter date in DD-MM-YYYY format.': 'Ingrese la fecha en formato DD-MM-AAAA.',
                'Only Tram/Bus stop field can be left empty.': 'Sólo el campo Parada de transporte publico puede dejarse vacío.',
                'Job applications sent out last week': 'Solicitudes de empleo enviadas la semana pasada',
                'Date': 'Fecha',
                'Job applications': 'Solicitudes de empleo',
                'Jobs per ': 'Empleos por ',
                'Categories': 'Categorías',
                'Job count': 'Solicitudes',
                'Settings': 'Ajustes',
                'Amount: ': 'Cantidad:',
                'Percent: ': 'Porcentaje: ',
            }
        }