from popups import *



class LanguageCenter:
    def __init__(self, lang):
        self.lang = lang
        self.dictionary = {
            'ENG': {
                "JOB HUNT HELPER": "JOB HUNT HELPER",
                'VIEW ALL': 'VIEW ALL',
                'ADD': 'ADD',
                'SAVE': 'SAVE',
                "SEARCH": "SEARCH",
                "EDIT": 'EDIT',
                'FIND': 'FIND',
                'SAVE CHANGES': 'SAVE CHANGES',
                'DELETE': 'DELETE',
                'MENU': 'MENU',
                'Job Name': 'Job Name',
                'Job Type': 'Job Type',
                'Public Transport': 'Public Transport',
                'Job Address': 'Job Address',
                'Date Applied': 'Date Applied',
                'Job Status': 'Job Status',
                "Job Name:": "Job Name:",
                "Job Type:": "Job Type:",
                "Tram/Bus stop:": "Tram/Bus stop:",
                "Job Address:": "Job Address:",
                "Date (DD-MM-YYYY):": "Date (DD-MM-YYYY):",
                "Job Status:": "Job Status:",
                "job name": "job name",
                "date": "date",
                "status": "status",
                "type": "type",
                "bus/tram stop": "bus/tram stop",
                "SEARCH BY": "SEARCH BY",
                "VIEW STATS": "VIEW STATS",
                'AVERAGE APPS PER DAY': 'AVERAGE APPS PER DAY',
                'JOBS PER STATUS': 'JOBS PER STATUS',
                'JOBS PER TYPE': 'JOBS PER TYPE',
                'JOBS PER DATE': 'JOBS PER DATE',
                'APPLICATIONS IN PAST WEEK': 'APPLICATIONS IN PAST WEEK',
                'SHOW CHART': 'SHOW CHART',
                'SHOW TABLE': 'SHOW TABLE',
                'No job data added yet': 'No job data added yet',
                'Please select a job to delete.': 'Please select a job to delete.',
                'Please select an option from the dropdown menu.': 'Please select an option from the dropdown menu.',
                'No entries found.': 'No entries found.',
                'No data found. Please add a job then try again.': 'No data found. Please add a job then try again.',
                'Please select a job to edit.': 'Please select a job to edit.',
                "HIDE CHART": "HIDE CHART",
                "HIDE TABLE": "HIDE TABLE",
                "Average Apps per Day:": "Average Apps per Day:",
                'Amount:': 'Amount:',
                'Percent:': 'Percent:',
                "Jobs per Status:": "Jobs per Status:",
                "Jobs per Type:": "Jobs per Type:",
                "Jobs per Date:": "Jobs per Date:",
                "Apps sent out last week:": "Apps sent out last week:",
                "CHOOSE LANGUAGE": "CHOOSE LANGUAGE",
                "SELECT LANGUAGE": "SELECT LANGUAGE",
                "Check if everything is correct": "Check if everything is correct",
                'Job Name: ': 'Job Name: ',
                'Job Type: ': 'Job Type: ',
                'Public Transport: ': 'Public Transport: ',
                'Job Address: ': 'Job Address: ',
                'Date Applied: ': 'Date Applied: ',
                'Job Status: ': 'Job Status: ',
                "Are you sure?": "Are you sure?",
                "Please duble check you want to proceed": "Please duble check you want to proceed",
                'Please enter date in DD-MM-YYYY format.': 'Please enter date in DD-MM-YYYY format.',
                'Only Tram/Bus stop field can be left empty.': 'Only Tram/Bus stop field can be left empty.',
                'Job applications sent out last week': 'Job applications sent out last week',
                'Date': 'Date',
                'Job applications':'Job applications',
                'Jobs per ': 'Jobs per ',
                'Categories': 'Categories',
                'Job count': 'Job count',
            },
            'PL': {
                "JOB HUNT HELPER": "ASYSTENT POSZUKIWANIA PRACY",
                'VIEW ALL': 'ZOBACZ WSZYSTKO',
                'ADD': 'DODAJ',
                'SAVE': 'ZAPISZ',
                "SEARCH": "ZNAJDŹ",
                "EDIT": 'EDYTUJ',
                'FIND': 'SZUKAJ',
                'SAVE CHANGES': 'ZAPISZ ZMIANY',
                'DELETE': 'USUŃ',
                'MENU': 'MENU',
                'Job Name': 'Nazwa Pracodawcy',
                'Job Type': 'Rodzaj Pracy',
                'Public Transport': 'Przystanki w pobliżu',
                'Job Address': 'Siedziba Pracy',
                'Date Applied': 'Data złożenia CV',
                'Job Status': 'Status',
                "Job Name:": "Nazwa Pracodawcy:",
                "Job Type:": "Rodzaj Pracy:",
                "Tram/Bus stop:": "Przystanki w pobliżu:",
                "Job Address:": "Siedziba Pracy:",
                "Date (DD-MM-YYYY):": "Data (DD-MM-RRRR):",
                "Job Status:": "Status:",
                "job name": "nazwa pracodawcy",
                "date": "data",
                "status": "status",
                "type": "rodzaj",
                "bus/tram stop": "przystanki",
                "SEARCH BY": "OPCJE",
                "VIEW STATS": "STATYSTYKI",
                'AVERAGE APPS PER DAY': 'ŚREDNIA CV/DZIEŃ',
                'JOBS PER STATUS': 'STATUS',
                'JOBS PER TYPE': 'RODZAJ',
                'JOBS PER DATE': 'DATA',
                'APPLICATIONS IN PAST WEEK': 'CV ZŁOŻONE PRZEZ OSTATNIE 7 DNI',
                'SHOW CHART': 'POKAŻ WYKRES',
                'SHOW TABLE': 'POKAŻ TABELE',
                'No job data added yet': 'Jeszcze nie dodano żadnej pracy',
                'Please select a job to delete.': 'Wybierz prace do usunięcia',
                'Please select an option from the dropdown menu.': 'Proszę wybierz jedną z opcji',
                'No entries found.': 'Nic nie znaleziono.',
                'No data found. Please add a job then try again.': 'Nie znaleziono nic. Proszę dodaj wpis i sprubój ponownie.',
                'Please select a job to edit.': 'Wybierz wpis aby edytować',
                "HIDE CHART": "SCHOWAJ WYKRES",
                "HIDE TABLE": "SCHOWAJ TABELE",
                "Average Apps per Day:": "Średnia CD/DZIEŃ:",
                'Amount:': 'Ilość:',
                'Percent:': 'Procent:',
                "Jobs per Status:": "Prace podzielone na status:",
                "Jobs per Type:": "Prace podzielone na rodzaj:",
                "Jobs per Date:": "Prace podzielone na date złorzenia CV:",
                "Apps sent out last week:": "CV złożone przez ostatnie 7 dni:",
                "CHOOSE LANGUAGE": "WYBIERZ JĘZYK",
                "SELECT LANGUAGE": "WYBIERZ JĘZYK",
                "Check if everything is correct": "Sprawdź czy wszystko się zgadza",
                'Job Name: ': 'Nazwa Pracodawcy: ',
                'Job Type: ': 'Rodzaj Pracy: ',
                'Public Transport: ': 'Przystanki w poblirzu: ',
                'Job Address: ': 'Siedziba Pracy: ',
                'Date Applied: ': 'Data złożenia CV: ',
                'Job Status: ': 'Status: ',
                "Are you sure?": "Czy jesteś pewny/a?",
                "Please duble check you want to proceed": "Contynuuj?",
                'Please enter date in DD-MM-YYYY format.': 'Proszę wpisać date w formacie DD-MM-RRRR',
                'Only Tram/Bus stop field can be left empty.': 'Tylko informacja o pobliskich przystankach może pozostać nieuzupełniona.',
                'Job applications sent out last week': 'CV złożone przez ostatnie 7 dni',
                'Date': 'Data',
                'Job applications': 'Złożone CV',
                'Jobs per ': 'Prace na ',
                'Categories': 'Kategorie',
                'Job count': 'Iloś złożonych CV',
            },
            'ES': {
                "JOB HUNT HELPER": "ASYSTENT POSZUKIWANIA PRACY",
                'VIEW ALL': 'ZOBACZ WSZYSTKO',
                'ADD': 'DODAJ',
                'SAVE': 'ZAPISZ',
                "SEARCH": "ZNAJDŹ",
                "EDIT": 'EDYTUJ',
                'FIND': 'SZUKAJ',
                'SAVE CHANGES': 'ZAPISZ ZMIANY',
                'DELETE': 'USUŃ',
                'MENU': 'MENU',
                'Job Name': 'Nazwa Pracodawcy',
                'Job Type': 'Rodzaj Pracy',
                'Public Transport': 'Przystanki w pobliżu',
                'Job Address': 'Siedziba Pracy',
                'Date Applied': 'Data złożenia CV',
                'Job Status': 'Status',
                "Job Name:": "Nazwa Pracodawcy:",
                "Job Type:": "Rodzaj Pracy:",
                "Tram/Bus stop:": "Przystanki w pobliżu:",
                "Job Address:": "Siedziba Pracy:",
                "Date (DD-MM-YYYY):": "Data (DD-MM-RRRR):",
                "Job Status:": "Status:",
                "job name": "nazwa pracodawcy",
                "date": "data",
                "status": "status",
                "type": "rodzaj",
                "bus/tram stop": "przystanki",
                "SEARCH BY": "OPCJE",
                "VIEW STATS": "STATYSTYKI",
                'AVERAGE APPS PER DAY': 'ŚREDNIA CV/DZIEŃ',
                'JOBS PER STATUS': 'STATUS',
                'JOBS PER TYPE': 'RODZAJ',
                'JOBS PER DATE': 'DATA',
                'APPLICATIONS IN PAST WEEK': 'CV ZŁOŻONE PRZEZ OSTATNIE 7 DNI',
                'SHOW CHART': 'POKAŻ WYKRES',
                'SHOW TABLE': 'POKAŻ TABELE',
                'No job data added yet': 'Jeszcze nie dodano żadnej pracy',
                'Please select a job to delete.': 'Wybierz prace do usunięcia',
                'Please select an option from the dropdown menu.': 'Proszę wybierz jedną z opcji',
                'No entries found.': 'Nic nie znaleziono.',
                'No data found. Please add a job then try again.': 'Nie znaleziono nic. Proszę dodaj wpis i sprubój ponownie.',
                'Please select a job to edit.': 'Wybierz wpis aby edytować',
                "HIDE CHART": "SCHOWAJ WYKRES",
                "HIDE TABLE": "SCHOWAJ TABELE",
                "Average Apps per Day:": "Średnia CD/DZIEŃ:",
                'Amount:': 'Ilość:',
                'Percent:': 'Procent:',
                "Jobs per Status:": "Prace podzielone na status:",
                "Jobs per Type:": "Prace podzielone na rodzaj:",
                "Jobs per Date:": "Prace podzielone na date złorzenia CV:",
                "Apps sent out last week:": "CV złożone przez ostatnie 7 dni:",
                "CHOOSE LANGUAGE": "WYBIERZ JĘZYK",
                "SELECT LANGUAGE": "WYBIERZ JĘZYK",
                "Check if everything is correct": "Sprawdź czy wszystko się zgadza",
                'Job Name: ': 'Nazwa Pracodawcy: ',
                'Job Type: ': 'Rodzaj Pracy: ',
                'Public Transport: ': 'Przystanki w poblirzu: ',
                'Job Address: ': 'Siedziba Pracy: ',
                'Date Applied: ': 'Data złożenia CV: ',
                'Job Status: ': 'Status: ',
                "Are you sure?": "Czy jesteś pewny/a?",
                "Please duble check you want to proceed": "Contynuuj?",
                'Please enter date in DD-MM-YYYY format.': 'Proszę wpisać date w formacie DD-MM-RRRR',
                'Only Tram/Bus stop field can be left empty.': 'Tylko informacja o pobliskich przystankach może pozostać nieuzupełniona.',
                'Job applications sent out last week': 'CV złożone przez ostatnie 7 dni',
                'Date': 'Data',
                'Job applications': 'Złożone CV',
                'Jobs per ': 'Prace na ',
                'Categories': 'Kategorie',
                'Job count': 'Iloś złożonych CV',
            }
        }

    def set_language(self):
        print(self.lang)
        return self.lang


    def translate(self, text):
        if self.lang:
            translated_text = self.dictionary[self.lang][text]
            print(translated_text)
            return translated_text
        else:
            return None